### ISSUE TITLE
Date string should use dashes

### ISSUE THREAD

**Issue by santilland** [eodash/eodash_catalog#14]
Some of the created datetime strings do not create them with dashes, e.g. `20200808` instead of `2020-08-08`.
This is the case at least for `GeoJSON source`, we need to either introduce a check or make sure we convert the datetime into a datetime object to make sure it is valid while generating the catalog.

**Comment by lubojr** [comment]
All ["datetime"] strings in extra links of items will be now isoformatted:
done in https://github.com/eodash/eodash_catalog/commit/17eb9f07ab92358b123e3472f04ef29522693f65
